image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
    - java -jar ./artifacts/app-card-delivery.jar -port=9999 &
    - java -jar ./artifacts/app-ibank.jar -port=7777 -P:profile=test &

build_script:
  - ./gradlew test --info

