image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

services:
  - docker

install:
  - ps: sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - ps: sudo chmod +x /usr/local/bin/docker-compose
  - ps: sudo docker-compose up -d
  - sleep 100
  - java -jar ./artifacts/app-deadline.jar &

test_script:
  - sudo chmod +x gradlew
  - ps: ./gradlew test --info

build_script:
  - sleep 100
  - sudo chmod +x ./gradlew
  - ./gradlew test --info

