image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - ps: sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - ps: sudo chmod +x /usr/local/bin/docker-compose
  - ps: sudo docker-compose up -d
  - sleep 10
  - java -jar ./artifacts/app-order.jar &

build_script:
  - ./gradlew test --info

